### PR TITLE
[TypeScript] Most complete with ES6 compatibility without changing source

### PR DESCRIPTION
**Pull request by roblav96**
These are the most complete definitions with maximum compatibility, without changing the codebase.

Merge it :shipit: =]

### CODE REVIEW

**Comment by scottcorgan** [comment]
@roblav96 super happy you did this. Can you show me some screenshots of this working? Then I'd be happy to merge it 👍

**Comment by jackturnbull** [comment]
@scottcorgan I've hit the same issue and I came across this PR, would I be able to ask you to try and get this integrated? Screenshots of my before/after below.

### Before (Typescript Import Error)
screen shot 2019-02-15 at 16 40 44
### After (Clean)
screen shot 2019-02-15 at 16 39 28

Minor, but you may wish to run a lint on this pre/post merge due to whitespace being tabs.

**Comment by OmgImAlexis** [comment]
@roblav96 any chance you want to update this to work with the latest changes?

**Comment by RZarifov** [comment]
Greetings guys. Any updates? @roblav96 @scottcorgan

**Pull request closed without merging**
